# Generated by Django 6.0.3 on 2026-03-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaOEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('quant_operadores', models.IntegerField(default=1)),
                ('custo_hora_operacional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producao_un_hora', models.IntegerField(default=1000)),
                ('setup_minutos', models.IntegerField(default=15)),
                ('faz_corte', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'maquina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterfallOEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_fixo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'waterfall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('largura_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comprimento_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipo_papelao', models.CharField(default='Onda B', max_length=50)),
                ('custo_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_producao', models.DecimalField(decimal_places=2, help_text='Ex: 70.00 para 70%', max_digits=5)),
                ('percentual_century', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentual_boca_sapo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appOrcam.maquinaoee')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(db_index=True, max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto_nome', models.CharField(default='Caixa de Pizza 35', max_length=100)),
                ('quantidade', models.PositiveIntegerField()),
                ('usou_corte_externo', models.BooleanField(default=False)),
                ('preco_final_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perda_material', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perda_processo_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chapa_ideal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideal_set', to='appOrcam.chapa')),
                ('chapa_utilizada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_set', to='appOrcam.chapa')),
                ('maquina_corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_corte', to='appOrcam.maquinaoee')),
                ('maquina_impressao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_impressao', to='appOrcam.maquinaoee')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
