# Generated by Django 6.0.3 on 2026-03-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorateio',
            name='percentual_seladora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
