# Generated by Django 6.0.3 on 2026-03-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0002_configuracaorateio_percentual_seladora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaorateio',
            name='percentual_seladora',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='perda_processo_extra',
        ),
        migrations.AddField(
            model_name='configuracaorateio',
            name='custo_hora_operacional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='configuracaorateio',
            name='producao_un_hora',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='margem_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='preco_final_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
