# Generated by Django 6.0.3 on 2026-03-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0003_remove_configuracaorateio_percentual_seladora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaFinancasOEE',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('maquina_id', models.BigIntegerField()),
                ('valor_reposicao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_minuto', models.DecimalField(decimal_places=6, max_digits=16)),
                ('minutos_mes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_mes', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'appoee_maquinafinancas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrosOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_tinta_m2', models.DecimalField(decimal_places=2, default=0.2, max_digits=10, verbose_name='Custo da Tinta (R$/m²)')),
            ],
            options={
                'verbose_name': 'Parâmetros Globais',
                'verbose_name_plural': 'Parâmetros Globais',
            },
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={},
        ),
    ]
