# Generated by Django 6.0.3 on 2026-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0004_maquinafinancasoee_parametrosorcamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrosorcamento',
            options={'verbose_name': 'Parâmetros Globais'},
        ),
        migrations.RemoveField(
            model_name='parametrosorcamento',
            name='custo_tinta_m2',
        ),
        migrations.AddField(
            model_name='parametrosorcamento',
            name='custo_tinta_unitario',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10, verbose_name='Custo da Tinta (R$ por unidade)'),
        ),
    ]
