# Generated by Django 6.0.3 on 2026-03-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0005_alter_parametrosorcamento_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametrosOrcamento',
            new_name='Custo_tinta',
        ),
        migrations.AlterModelOptions(
            name='custo_tinta',
            options={'verbose_name': 'Parâmetro Orcamento_tinta'},
        ),
    ]
