# Generated by Django 6.0.3 on 2026-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0006_rename_parametrosorcamento_custo_tinta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo_frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_frete_unitario', models.DecimalField(decimal_places=2, default=0.2, max_digits=10, verbose_name='Custo do Frete (R$ por unidade)')),
            ],
            options={
                'verbose_name': 'Custo Frete',
            },
        ),
        migrations.AlterModelOptions(
            name='custo_tinta',
            options={'verbose_name': 'Custo Tinta'},
        ),
    ]
