# Generated by Django 6.0.3 on 2026-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0007_custo_frete_alter_custo_tinta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_frete_unitario',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=10, verbose_name='Frete por Unidade'),
        ),
        migrations.AlterField(
            model_name='custo_frete',
            name='custo_frete_unitario',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=10, verbose_name='Custo do Frete (R$ por unidade)'),
        ),
    ]
