# Generated by Django 6.0.3 on 2026-03-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0008_orcamento_custo_frete_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='corte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_cortes', to='appOrcam.maquinaoee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='impressora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_impressora', to='appOrcam.maquinaoee'),
            preserve_default=False,
        ),
    ]
