# Generated by Django 6.0.3 on 2026-03-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0029_alter_maquina_corte_alter_maquina_impressora'),
        ('appOrcam', '0009_orcamento_corte_orcamento_impressora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='impressora',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_corte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_maquina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='maquina_corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_corte', to='appOEE.maquina'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='maquina_impressao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_impressao', to='appOEE.maquina'),
        ),
    ]
