# Generated by Django 6.0.3 on 2026-03-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0010_remove_orcamento_corte_remove_orcamento_impressora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='custo_maquina',
            new_name='custo_impressao',
        ),
    ]
