# Generated by Django 6.0.3 on 2026-03-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0011_rename_custo_maquina_orcamento_custo_impressao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='custo_corte',
        ),
    ]
