# Generated by Django 6.0.3 on 2026-03-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0012_remove_orcamento_custo_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='custo_impressao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
