# Generated by Django 6.0.3 on 2026-03-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0013_alter_orcamento_custo_impressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='custo_impressao',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOrcam.maquinafinancasoee'),
        ),
    ]
