# Generated by Django 6.0.3 on 2026-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0016_alter_orcamento_custo_impressao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_corte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
