# Generated by Django 6.0.3 on 2026-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0017_orcamento_custo_corte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='usou_corte_externo',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_maquinas',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='custo_corte',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='custo_impressao',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
