# Generated by Django 6.0.3 on 2026-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0018_remove_orcamento_usou_corte_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_material_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
