# Generated by Django 6.0.3 on 2026-03-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0019_orcamento_custo_material_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='unidades_chapa',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades por Chapa'),
        ),
    ]
