# Generated by Django 6.0.3 on 2026-03-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0020_orcamento_unidades_chapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_seladora',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
