# Generated by Django 6.0.3 on 2026-03-16 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0029_alter_maquina_corte_alter_maquina_impressora'),
        ('appOrcam', '0021_orcamento_custo_seladora'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='maquina_seladora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_seladora', to='appOEE.maquina'),
        ),
    ]
