# Generated by Django 6.0.3 on 2026-03-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0022_orcamento_maquina_seladora'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='gramatura_kg_m2',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=7),
        ),
        migrations.AddField(
            model_name='chapa',
            name='larg_apara_cm',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=7),
        ),
        migrations.AddField(
            model_name='chapa',
            name='preco_apara_kg',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=7),
        ),
    ]
