# Generated by Django 6.0.3 on 2026-03-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0023_chapa_gramatura_kg_m2_chapa_larg_apara_cm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapa',
            old_name='larg_apara_cm',
            new_name='larg_apara_m',
        ),
    ]
