# Generated by Django 6.0.3 on 2026-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0024_rename_larg_apara_cm_chapa_larg_apara_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='preco_kg_compra',
            field=models.DecimalField(decimal_places=2, default=1.78, max_digits=7),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='perda_excedente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='perda_ideal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
