# Generated by Django 6.0.3 on 2026-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0025_chapa_preco_kg_compra_orcamento_perda_excedente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='chapa_ideal',
            new_name='chapa_projeto',
        ),
        migrations.RenameField(
            model_name='orcamento',
            old_name='perda_ideal',
            new_name='perda_projeto',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='perda_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
