# Generated by Django 6.0.3 on 2026-03-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0026_rename_chapa_ideal_orcamento_chapa_projeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='perda_excedente',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='perda_material',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='perda_projeto',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='perda_real',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='area_perda_projeto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='area_projeto_liquida',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='area_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_perda_excedente',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_perda_projeto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_perda_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='perda_area_excedente',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='perda_area_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
