# Generated by Django 6.0.3 on 2026-03-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0027_remove_orcamento_perda_excedente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto (ex: Bolo 1kg)')),
                ('largura_aberta_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comprimento_aberta_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantidade_minima', models.PositiveIntegerField(default=500)),
                ('chapa_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOrcam.chapa')),
            ],
        ),
    ]
