# Generated by Django 6.0.3 on 2026-03-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0028_produtopadrao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtopadrao',
            old_name='comprimento_aberta_cm',
            new_name='comprimento_chapa_aberta_cm',
        ),
        migrations.RenameField(
            model_name='produtopadrao',
            old_name='largura_aberta_cm',
            new_name='largura_chapa_aberta_cm',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_papelao',
            field=models.CharField(blank=True, default='Onda B', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produtopadrao',
            name='explicacao_tecnica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtopadrao',
            name='medida_caixa_montada',
            field=models.CharField(default='0x0x0', max_length=50, verbose_name='Medida Montada (cm)'),
        ),
        migrations.AddField(
            model_name='produtopadrao',
            name='tipo_papelao',
            field=models.CharField(default='Onda E', max_length=50),
        ),
        migrations.AddField(
            model_name='produtopadrao',
            name='unidades_chapa',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades por Chapa'),
        ),
        migrations.AlterField(
            model_name='produtopadrao',
            name='chapa_sugerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOrcam.chapa', verbose_name='Chapa Padrão (Onda E, etc.)'),
        ),
        migrations.AlterField(
            model_name='produtopadrao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
    ]
