# Generated by Django 6.0.3 on 2026-03-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0029_rename_comprimento_aberta_cm_produtopadrao_comprimento_chapa_aberta_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='explicacao_tecnica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chapa',
            name='medida_caixa_montada_cm',
            field=models.CharField(default='0x0x0', max_length=50, verbose_name='Medida Montada (cm)'),
        ),
        migrations.AddField(
            model_name='chapa',
            name='unidades_chapa',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades por Chapa'),
        ),
    ]
