# Generated by Django 6.0.3 on 2026-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0030_chapa_explicacao_tecnica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapa',
            name='preco_kg_compra',
        ),
    ]
