# Generated by Django 6.0.3 on 2026-03-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0031_remove_chapa_preco_kg_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoPadrao',
        ),
    ]
