# Generated by Django 6.0.3 on 2026-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0032_delete_produtopadrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
