# Generated by Django 6.0.3 on 2026-03-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0033_categoriaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='CategoriaProduto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOrcam.categoriaproduto'),
        ),
    ]
