# Generated by Django 6.0.3 on 2026-03-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0034_orcamento_categoriaproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='CategoriaProduto',
            new_name='categoria_produto',
        ),
    ]
