# Generated by Django 6.0.3 on 2026-03-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0035_rename_categoriaproduto_orcamento_categoria_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='tipo_papelao',
            new_name='tipo_papelao_db',
        ),
    ]
