# Generated by Django 6.0.3 on 2026-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0036_rename_tipo_papelao_orcamento_tipo_papelao_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_tinta_unitario',
            field=models.DecimalField(decimal_places=4, default=0.2, max_digits=10),
        ),
    ]
