# Generated by Django 6.0.3 on 2026-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0037_orcamento_custo_tinta_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteUnidadesProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contem', models.CharField(help_text='Termo para busca no nome do produto (ex: Pizza)', max_length=100)),
                ('unidade_maxima', models.PositiveIntegerField()),
            ],
        ),
    ]
