# Generated by Django 6.0.3 on 2026-04-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0038_limiteunidadesproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimiteUnidadesProduto',
        ),
    ]
