# Generated by Django 6.0.3 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0039_delete_limiteunidadesproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaCalculoDinamica',
            fields=[
                ('maquina_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome_maquina', models.CharField(max_length=50)),
                ('valor_reposicao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('participacao_real', models.DecimalField(decimal_places=6, max_digits=15)),
                ('custo_fixo_total_ref', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_minuto_real', models.DecimalField(decimal_places=4, max_digits=16)),
            ],
            options={
                'db_table': 'view_memoria_calculo_dinamica',
                'managed': False,
            },
        ),
    ]
