# Generated by Django 6.0.3 on 2026-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0041_imposto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='aliquota_imposto_aplicada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='preco_final_com_nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='preco_final_sem_nota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='venda_com_nota',
            field=models.BooleanField(default=False, verbose_name='Venda com Nota Fiscal?'),
        ),
    ]
