# Generated by Django 6.0.3 on 2026-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0042_orcamento_aliquota_imposto_aplicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncargosTrabalhistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo_no_calculo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
