# Generated by Django 6.0.4 on 2026-04-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0043_encargostrabalhistas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquinafinancasoee',
            table='appOEE_maquinafinancas',
        ),
    ]
