# Generated by Django 6.0.5 on 2026-06-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0044_alter_maquinafinancasoee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maquinaoee',
            table='appOEE_maquina',
        ),
    ]
