# Generated by Django 6.0.5 on 2026-06-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0045_alter_maquinaoee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=100, verbose_name='Nome do Vendedor')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão (%)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comissão de Venda',
                'verbose_name_plural': 'Comissões de Vendas',
                'db_table': 'appOrcam_comissao_venda',
            },
        ),
    ]
