# Generated by Django 6.0.5 on 2026-06-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0046_comissaovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_papelao_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
