# Generated by Django 6.0.5 on 2026-06-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0047_orcamento_custo_papelao_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='custo_total_tinta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Custo Total da Tinta'),
        ),
    ]
