# Generated by Django 6.0.5 on 2026-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0048_orcamento_custo_total_tinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='prolabore_socio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
