# Generated by Django 6.0.5 on 2026-08-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0049_orcamento_prolabore_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapa',
            name='altura_pacote_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='chapa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapa',
            name='comprim_pacote_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='chapa',
            name='largura_pacote_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='chapa',
            name='peso_pacote',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='chapa',
            name='unidades_pacote',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
