# Generated by Django 6.0.5 on 2026-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0050_chapa_altura_pacote_cm_chapa_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa / Cliente')),
                ('nome_contato', models.CharField(max_length=150, verbose_name='Nome do Contato')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone / WhatsApp')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('resumo_pedido', models.TextField(verbose_name='Resumo da Cotação')),
                ('valor_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo (Aguardando Contato)'), ('EM_ATENDIMENTO', 'Em Negociação'), ('FECHADO_GANHO', 'Venda Fechada'), ('FECHADO_PERDIDO', 'Venda Perdida')], default='NOVO', max_length=20, verbose_name='Status de Atendimento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data da Cotação')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead de Orçamento',
                'verbose_name_plural': 'Leads de Orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
