# Generated by Django 6.0.5 on 2026-09-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrcam', '0051_leadorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadorcamento',
            name='vendedor_responsavel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Vendedor Responsável'),
        ),
    ]
