# Generated by Django 6.0.3 on 2026-04-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('cliente', models.CharField(max_length=200)),
                ('cep_destino', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('peso_informado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_cubado', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_nf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pacotes', models.IntegerField()),
                ('total_unidades', models.IntegerField()),
                ('total_volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LogTransportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('frete_id', models.IntegerField()),
                ('transportadora_nome', models.CharField(max_length=150)),
                ('valor_antigo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItensFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qt_pacotes', models.IntegerField()),
                ('qt_unidades', models.IntegerField()),
                ('volume_item', models.DecimalField(decimal_places=4, max_digits=10)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='appFrete.detalhesfrete')),
            ],
        ),
        migrations.CreateModel(
            name='TransportadorasFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_transportadora', models.CharField(max_length=150)),
                ('regiao', models.CharField(max_length=100)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete_unidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportadoras', to='appFrete.detalhesfrete')),
            ],
        ),
    ]
