# Generated by Django 6.0.3 on 2026-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFrete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhesfrete',
            name='uf_coluna',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
