# Generated by Django 6.0.4 on 2026-04-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFrete', '0002_detalhesfrete_uf_coluna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhesfrete',
            name='cep_destino',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
