# Generated by Django 6.0.4 on 2026-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFrete', '0003_alter_detalhesfrete_cep_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCapitalBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('capital', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FreteEdne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_index=True, max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(db_index=True, max_length=100)),
                ('municipio_cod_ibge', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'app_frete_edne',
            },
        ),
        migrations.CreateModel(
            name='TransportadoraFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=50)),
                ('transportadora', models.CharField(db_index=True, max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('estado_sigla', models.CharField(db_index=True, max_length=2)),
                ('cem_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='100_kg')),
                ('cento_cinquenta_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='150_kg')),
                ('duzentos_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='200_kg')),
                ('frete_peso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fator_excedente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fator_sp_capital', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguro_risso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ad_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ad_valor_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gris', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gris_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxa_emb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedagio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suframa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguro_fluvial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fator_risso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icms', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emex', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_adm_fin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('antt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prazo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TransportadorasFrete',
            new_name='TabelaFreteTransportadora',
        ),
    ]
