# Generated by Django 6.0.5 on 2026-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFrete', '0004_estadocapitalbr_freteedne_transportadorafrete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhesfrete',
            name='prazo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
