# Generated by Django 6.0.5 on 2026-07-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFrete', '0005_detalhesfrete_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhesfrete',
            name='prazo',
        ),
        migrations.AddField(
            model_name='tabelafretetransportadora',
            name='prazo',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='transportadorafrete',
            name='prazo',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
