# Generated by Django 6.0 on 2025-12-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=26)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reclam', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=250)),
                ('id_defeito', models.IntegerField(choices=[(1, 'baixa resistência do papelão'), (2, 'caixa avariada'), (3, 'cheiro na embalagem'), (4, 'desfolhamento do papelão'), (5, 'embalagem com defeito'), (6, 'entrega atrasada'), (7, 'entrega incompleta'), (8, 'impressão borrada _ tonalidade variando _ falha'), (9, 'falta parte da tampa'), (10, 'impressão fora de centro_esquadro'), (11, 'lacre não cola _ fora de posição'), (12, 'mistura de produtos'), (13, 'rasgamento na dobra'), (14, 'tampa redonda fora de medida'), (15, 'trava ausente ou não encaixa')], default='impressão borrada _ tonalidade variando _ falha')),
                ('vendedora', models.CharField(max_length=12)),
                ('id_produto', models.IntegerField(choices=[(1, 'caixa de bolo'), (2, 'caixa de esfiha'), (3, 'caixa de pizza 25'), (4, 'caixa de pizza 30'), (5, 'caixa de pizza 35'), (6, 'caixa de pizza 40'), (7, 'caixa de pizza broto'), (8, 'caixa de vinho'), (9, 'fatia de pizza'), (10, 'maleta de vinho'), (11, 'sanduIche de pão por metro'), (12, 'embalagens especiais'), (13, 'embalagens de doces')], default='caixa de pizza 35')),
                ('id_tecnol', models.IntegerField(choices=[(1, 'flexografia'), (2, 'OffSet'), (3, 'flexocromia w1'), (4, 'flexocromia w2')], default='flexografia')),
                ('id_empresa', models.IntegerField(choices=[(1, 'Senhor Caixa'), (2, 'Doutor Caixa')], default='Senhor Caixa')),
                ('comentarios', models.CharField(blank=True, max_length=193, null=True)),
                ('data_atualiza', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Reclamacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tecnologia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tecnologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDefeitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_defeito', models.CharField(max_length=49)),
            ],
            options={
                'db_table': 'tipos_defeitos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReclamacoesArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='itens/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('reclamacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='appQuali.reclamacoes')),
            ],
        ),
    ]
