# Generated by Django 6.0 on 2025-12-28 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamacoesarquivo',
            old_name='image',
            new_name='itens',
        ),
        migrations.AlterField(
            model_name='reclamacoesarquivo',
            name='reclamacoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='appQuali.reclamacoes'),
        ),
    ]
