# Generated by Django 6.0 on 2025-12-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0002_rename_image_reclamacoesarquivo_itens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoesarquivo',
            name='itens',
            field=models.FileField(upload_to='itens', verbose_name='Arquivos / Anexos: '),
        ),
    ]
