# Generated by Django 6.0 on 2026-01-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0003_alter_reclamacoesarquivo_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamacoesarquivo',
            name='itens',
            field=models.FileField(blank=True, null=True, upload_to='itens', verbose_name='Arquivos / Anexos: '),
        ),
    ]
