# Generated by Django 6.0 on 2026-01-09 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0004_alter_reclamacoesarquivo_itens'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField(help_text='O número da semana no ano (1-53).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('ano', models.PositiveIntegerField(help_text='Ano de 2026 à 2036.', validators=[django.core.validators.MinValueValidator(2026), django.core.validators.MaxValueValidator(2036)])),
            ],
        ),
    ]
