# Generated by Django 6.0 on 2026-01-09 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0005_semanano'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanano',
            name='data_fim',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='semanano',
            name='data_inicio',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='semanano',
            name='ano',
            field=models.PositiveIntegerField(help_text='Ano de 2025 à 2100.', validators=[django.core.validators.MinValueValidator(2025), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
