# Generated by Django 6.0.5 on 2026-05-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0006_semanano_data_fim_semanano_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanano',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semanano',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
