# Generated by Django 6.0.5 on 2026-06-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0007_alter_semanano_data_fim_alter_semanano_data_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamacoesarquivo',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='reclamacoes',
            table='reclamacoes',
        ),
    ]
