# Generated by Django 6.0.5 on 2026-06-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appQuali', '0008_alter_reclamacoesarquivo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reclamacoesarquivo',
            table='appquali_reclamacoesarquivo',
        ),
    ]
