# Generated by Django 6.0.1 on 2026-02-02 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_mes', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, unique=True)),
            ],
            options={
                'db_table': 'dia_mes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Horas_turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_horas_turno', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, unique=True)),
            ],
            options={
                'db_table': 'horas_turno',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'maquina',
            },
        ),
        migrations.CreateModel(
            name='Mes_ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, unique=True)),
            ],
            options={
                'db_table': 'mes_ano',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'motivo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipo_parada',
            },
        ),
        migrations.CreateModel(
            name='Turnos_dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_turnos_dia', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, unique=True)),
            ],
            options={
                'db_table': 'turnos_dia',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('qualidade', models.IntegerField(default=100)),
                ('performance', models.IntegerField(default=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.empresa')),
                ('horas_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.horas_turno')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.maquina')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.motivo')),
                ('tipo_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.tipo_parada')),
                ('turnos_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOEE.turnos_dia')),
            ],
        ),
        migrations.CreateModel(
            name='Calc_roce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.IntegerField(blank=True, choices=[(40, '40%'), (41, '41%'), (42, '42%'), (43, '43%'), (44, '44%'), (45, '45%'), (46, '46%'), (47, '47%'), (48, '48%'), (49, '49%'), (50, '50%'), (51, '51%'), (52, '52%'), (53, '53%'), (54, '54%'), (55, '55%'), (56, '56%'), (57, '57%'), (58, '58%'), (59, '59%'), (60, '60%'), (61, '61%'), (62, '62%'), (63, '63%'), (64, '64%'), (65, '65%'), (66, '66%'), (67, '67%'), (68, '68%'), (69, '69%'), (70, '70%'), (71, '71%'), (72, '72%'), (73, '73%'), (74, '74%'), (75, '75%'), (76, '76%'), (77, '77%'), (78, '78%'), (79, '79%'), (80, '80%'), (81, '81%'), (82, '82%'), (83, '83%'), (84, '84%'), (85, '85%'), (86, '86%'), (87, '87%'), (88, '88%'), (89, '89%'), (90, '90%'), (91, '91%'), (92, '92%'), (93, '93%'), (94, '94%'), (95, '95%'), (96, '96%'), (97, '97%'), (98, '98%'), (99, '99%'), (100, '100%')], null=True)),
                ('performance', models.IntegerField(blank=True, choices=[(40, '40%'), (41, '41%'), (42, '42%'), (43, '43%'), (44, '44%'), (45, '45%'), (46, '46%'), (47, '47%'), (48, '48%'), (49, '49%'), (50, '50%'), (51, '51%'), (52, '52%'), (53, '53%'), (54, '54%'), (55, '55%'), (56, '56%'), (57, '57%'), (58, '58%'), (59, '59%'), (60, '60%'), (61, '61%'), (62, '62%'), (63, '63%'), (64, '64%'), (65, '65%'), (66, '66%'), (67, '67%'), (68, '68%'), (69, '69%'), (70, '70%'), (71, '71%'), (72, '72%'), (73, '73%'), (74, '74%'), (75, '75%'), (76, '76%'), (77, '77%'), (78, '78%'), (79, '79%'), (80, '80%'), (81, '81%'), (82, '82%'), (83, '83%'), (84, '84%'), (85, '85%'), (86, '86%'), (87, '87%'), (88, '88%'), (89, '89%'), (90, '90%'), (91, '91%'), (92, '92%'), (93, '93%'), (94, '94%'), (95, '95%'), (96, '96%'), (97, '97%'), (98, '98%'), (99, '99%'), (100, '100%')], db_column='performance', null=True)),
                ('disponibilidade', models.IntegerField(blank=True, choices=[(40, '40%'), (41, '41%'), (42, '42%'), (43, '43%'), (44, '44%'), (45, '45%'), (46, '46%'), (47, '47%'), (48, '48%'), (49, '49%'), (50, '50%'), (51, '51%'), (52, '52%'), (53, '53%'), (54, '54%'), (55, '55%'), (56, '56%'), (57, '57%'), (58, '58%'), (59, '59%'), (60, '60%'), (61, '61%'), (62, '62%'), (63, '63%'), (64, '64%'), (65, '65%'), (66, '66%'), (67, '67%'), (68, '68%'), (69, '69%'), (70, '70%'), (71, '71%'), (72, '72%'), (73, '73%'), (74, '74%'), (75, '75%'), (76, '76%'), (77, '77%'), (78, '78%'), (79, '79%'), (80, '80%'), (81, '81%'), (82, '82%'), (83, '83%'), (84, '84%'), (85, '85%'), (86, '86%'), (87, '87%'), (88, '88%'), (89, '89%'), (90, '90%'), (91, '91%'), (92, '92%'), (93, '93%'), (94, '94%'), (95, '95%'), (96, '96%'), (97, '97%'), (98, '98%'), (99, '99%'), (100, '100%')], db_column='disponibilidade', null=True)),
                ('valor_ativos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deprec_ano_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manut_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('qt_pessoas', models.IntegerField(blank=True, null=True)),
                ('salario_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('encargos_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('benef_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('outros_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dia_mes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calc_roce', to='appOEE.dia_mes')),
                ('horas_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calc_roce', to='appOEE.horas_turno')),
                ('mes_ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calc_roce', to='appOEE.mes_ano')),
                ('turnos_dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calc_roce', to='appOEE.turnos_dia')),
            ],
            options={
                'db_table': 'calc_roce',
            },
        ),
    ]
