# Generated by Django 6.0.1 on 2026-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='tempo_parado',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
