# Generated by Django 6.0.1 on 2026-02-04 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0004_alter_ocorrencia_disponibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaFinancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_reposicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('custo_minuto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maquina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financas', to='appOEE.maquina')),
            ],
            options={
                'db_table': 'appoee_maquinafinancas',
            },
        ),
    ]
