# Generated by Django 6.0.1 on 2026-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0005_maquinafinancas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_grupo', models.DecimalField(decimal_places=2, default=4300000.0, max_digits=15)),
                ('percentual_empresa_estudo', models.DecimalField(decimal_places=2, default=65.0, max_digits=5)),
                ('quantidade_pessoas', models.IntegerField(default=65)),
                ('salario_medio', models.DecimalField(decimal_places=2, default=2200.0, max_digits=10)),
                ('encargos_trabalhistas_pct', models.DecimalField(decimal_places=2, default=67.0, max_digits=5)),
                ('beneficios_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('outros_custos_fixos_pct', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('retirada_socio_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('aluguel_iptu_total', models.DecimalField(decimal_places=2, default=140000.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Parâmetro Financeiro',
                'verbose_name_plural': 'Parâmetros Financeiros',
            },
        ),
        migrations.DeleteModel(
            name='Calc_roce',
        ),
    ]
