# Generated by Django 6.0.1 on 2026-02-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0006_parametrofinanceiro_delete_calc_roce'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='custo_variav_fatur_real_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='prestacoes_investimentos',
            field=models.DecimalField(decimal_places=2, default=300000.0, max_digits=15),
        ),
    ]
