# Generated by Django 6.0.1 on 2026-02-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0007_parametrofinanceiro_custo_variav_fatur_real_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivo',
            name='tipo_parada_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOEE.tipo_parada'),
        ),
    ]
