# Generated by Django 6.0.1 on 2026-02-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0008_motivo_tipo_parada_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivo',
            old_name='tipo_parada_id',
            new_name='tipo_parada',
        ),
    ]
