# Generated by Django 6.0.1 on 2026-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0009_rename_tipo_parada_id_motivo_tipo_parada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('perda_oee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fat_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cust_var', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cust_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('res_contab', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cust_inefic', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('res_econom', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'waterfall',
            },
        ),
    ]
