# Generated by Django 6.0.1 on 2026-02-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0010_waterfall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterfall',
            old_name='cust_inefic',
            new_name='perda_disp',
        ),
        migrations.AddField(
            model_name='waterfall',
            name='perda_perf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='waterfall',
            name='perda_quali',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
