# Generated by Django 6.0.1 on 2026-02-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0011_rename_cust_inefic_waterfall_perda_disp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='cust_inefic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
