# Generated by Django 6.0.1 on 2026-02-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0012_waterfall_cust_inefic'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='oee_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='waterfall',
            name='socio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
