# Generated by Django 6.0.1 on 2026-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0013_waterfall_oee_atual_waterfall_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='ativos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
