# Generated by Django 6.0.1 on 2026-02-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0015_waterfall_hr_paralis'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinafinancas',
            name='dias_sem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maquinafinancas',
            name='horas_turno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maquinafinancas',
            name='sem_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='maquinafinancas',
            name='turnos_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='maquinafinancas',
            name='custo_minuto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
