# Generated by Django 6.0.1 on 2026-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0016_maquinafinancas_dias_sem_maquinafinancas_horas_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinafinancas',
            name='horas_mes',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=7, null=True),
        ),
    ]
