# Generated by Django 6.0.1 on 2026-02-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0017_maquinafinancas_horas_mes'),
    ]

    operations = [
    ]
