# Generated by Django 6.0.1 on 2026-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0018_auto_20260219_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinafinancas',
            name='minutos_mes',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
