# Generated by Django 6.0.1 on 2026-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0019_maquinafinancas_minutos_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinafinancas',
            name='custo_minuto',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='maquinafinancas',
            name='minutos_mes',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
