# Generated by Django 6.0.1 on 2026-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0020_alter_maquinafinancas_custo_minuto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='minutos_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
