# Generated by Django 6.0.1 on 2026-02-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0021_waterfall_minutos_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='depreciacao_mensal',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='manutencoes_mensais',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=15),
        ),
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='servicos_terceirizados_mensal',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=15),
        ),
    ]
