# Generated by Django 6.0.1 on 2026-02-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0022_parametrofinanceiro_depreciacao_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=2.6, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='quantidade_vendida',
            field=models.IntegerField(default=1720000),
        ),
        migrations.AlterField(
            model_name='parametrofinanceiro',
            name='faturamento_grupo',
            field=models.DecimalField(decimal_places=2, default=4472000.0, max_digits=15),
        ),
    ]
