# Generated by Django 6.0.1 on 2026-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0023_parametrofinanceiro_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrofinanceiro',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=2.6, max_digits=10),
        ),
    ]
