# Generated by Django 6.0.1 on 2026-02-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0024_alter_parametrofinanceiro_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinafinancas',
            name='perc_ativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
