# Generated by Django 6.0.1 on 2026-03-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0025_maquinafinancas_perc_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='corte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='impressora',
            field=models.IntegerField(default=1),
        ),
    ]
