# Generated by Django 6.0.1 on 2026-03-08 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0026_maquina_corte_maquina_impressora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='corte',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='impressora',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
