# Generated by Django 6.0.1 on 2026-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0027_alter_maquina_corte_alter_maquina_impressora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='corte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='impressora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
