# Generated by Django 6.0.1 on 2026-03-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0028_alter_maquina_corte_alter_maquina_impressora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='corte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='impressora',
            field=models.BooleanField(default=False),
        ),
    ]
