# Generated by Django 6.0.3 on 2026-04-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0029_alter_maquina_corte_alter_maquina_impressora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinafinancas',
            name='maquina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financas_oee', to='appOEE.maquina'),
        ),
    ]
