# Generated by Django 6.0.3 on 2026-04-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0030_alter_maquinafinancas_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='seladora',
            field=models.BooleanField(default=False),
        ),
    ]
