# Generated by Django 6.0.4 on 2026-04-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0031_maquina_seladora'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dia_mes',
            table='appOEE_dia_mes',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='appOEE_empresa',
        ),
        migrations.AlterModelTable(
            name='horas_turno',
            table='appOEE_horas_turno',
        ),
        migrations.AlterModelTable(
            name='maquina',
            table='appOEE_maquina',
        ),
        migrations.AlterModelTable(
            name='maquinafinancas',
            table='appOEE_maquinafinancas',
        ),
        migrations.AlterModelTable(
            name='mes_ano',
            table='appOEE_mes_ano',
        ),
        migrations.AlterModelTable(
            name='motivo',
            table='appOEE_motivo',
        ),
        migrations.AlterModelTable(
            name='tipo_parada',
            table='appOEE_tipo_parada',
        ),
        migrations.AlterModelTable(
            name='turnos_dia',
            table='appOEE_turnos_dia',
        ),
        migrations.AlterModelTable(
            name='waterfall',
            table='appOEE_waterfall',
        ),
    ]
