# Generated by Django 6.0.5 on 2026-06-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0032_alter_dia_mes_table_alter_empresa_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinafinancas',
            name='fator_k',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador comercial. Ex: 0.89 para reduzir ou 4.50 para aumentar.', max_digits=4, verbose_name='Fator K Comercial'),
        ),
    ]
