# Generated by Django 6.0.5 on 2026-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0033_maquinafinancas_fator_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='margem_calc_socio_pct',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
    ]
