# Generated by Django 6.0.5 on 2026-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOEE', '0034_parametrofinanceiro_margem_calc_socio_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrofinanceiro',
            name='refugo_perdas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Refugo e Perdas (%)'),
        ),
    ]
