"""
Django settings for prj_orcam project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from django.contrib.messages import constants as messages
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Adiciona a pasta raiz ao caminho de busca do Python
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i(y8++4r_-&z3%d#ejgq1sfj($r#%(lz6ji1qe1cba)x20(wki'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['82.25.71.95', 'localhost', '127.0.0.1',
                 'joinvia.app.br', 'www.joinvia.app.br', 
                 'packmetric.com.br', 'www.packmetric.com.br', 
                 'packmetric.app.br', 'www.packmetric.app.br']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appOrcam',
    'appOEE',
    'appFrete',
    'appQuali',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # A sua nova muralha global:
    'prj_orcam.middleware.LoginRequiredMiddleware',
]

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

ROOT_URLCONF = 'prj_orcam.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'appOrcam.context_processors.estatisticas_orcamentos',
            ],
        },
    },
]

WSGI_APPLICATION = 'prj_orcam.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.mysql",
        'NAME': "oee_bd",
        'USER': "root",
        'PASSWORD': "jjokocha@!7157",
        'HOST': "localhost",
        'PORT': 3306,
        'CONN_MAX_AGE': 600,  # Mantém a conexão viva por 10 minutos
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. Onde o navegador busca os arquivos (URL)
STATIC_URL = '/static/'

# 2. Deixe o STATICFILES_DIRS em branco (apenas os colchetes), 
# removendo qualquer linha que mencione a pasta 'static' principal para evitar o erro E002.
STATICFILES_DIRS = [
    # Apenas pastas de estáticos globais que NÃO sejam a STATIC_ROOT
]

# 3. Onde o Django vai reunir tudo para produção (CUIDADO: SEM colchetes aqui)
# Mude o nome da pasta final para 'staticfiles' para não dar conflito
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Informe ao Django qual é a URL de login do seu projeto
LOGIN_URL = 'login'            # Usamos o 'name' que definimos no urls.py
LOGIN_REDIRECT_URL = '/frete/' # Aqui está perfeito, manda para o app de frete
LOGOUT_REDIRECT_URL = 'login'  # Ao sair, ele volta para a tela de login

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

SESSION_SAVE_EVERY_REQUEST = False
